### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by arthurvr** [partydelgado/ama#1]

**Comment by partydelgado** [comment]
Why, [Refinery29](https://github.com/refinery29) of course :) But seriously, though most of our contributions are private, we're moving to open sourcing more and more of our projects, including this [jquery-ooyala](https://github.com/refinery29/jquery-ooyala) plugin built by our mobile team. I'm very proud of this and love seeing our team contributing to the community.

Otherwise, I'm really having fun playing with [React Native](https://github.com/facebook/react-native). I mean, javascript that compiles to native views? Come on, that's awesome.
